# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitFeed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitFeed
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'Kingfisher', '~> 3.2.2'

end

